# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f5bb354841fb65f48776f60f66ab33f04497fa7b601130389c61c7ba87fe8664f109e908797c32c9179eeff1331ee539adc156f37d6d7fd27b568f687a8d55a

test:
  secret_key_base: 52143afa7b5db9c038421429c38c587b4930280c72a77bc629769692dda3877fbdf8c6ba7229b0c59eeb8820a4d8a341c9b18486ba49f2cad781354dc870d6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
